=== saadehm80/XML-DTD-XSLT/Mondat/mandat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="rapport">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="mandat" minOccurs="1" maxOccurs="60" type="T_MANDAT">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="T_MANDAT">
        <xsd:sequence><!-- Choice: l'un ou l'autre, Sequence: ordre, All: non ordre -->
            <xsd:element name="expediteur" type="T_ED"> </xsd:element>
            <xsd:element name="destinateur" type="T_ED"> </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="num" type="xsd:int" use="required"> </xsd:attribute>
        <xsd:attribute name="date" type="xsd:date" use="required"> </xsd:attribute>
        <xsd:attribute name="montant" type="xsd:int" use="required"> 
        <xsd:simpleType>
            <xsd:restriction base="xsd:double">
                <xsd:minInclusive value="50"></xsd:minInclusive>
                <xsd:maxInclusive value="20000"></xsd:maxInclusive>
            </xsd:restriction>
        </xsd:simpleType>
        </xsd:attribute>

        <xsd:attribute name="etat" default="NON RECU">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="RECU"></xsd:enumeration>
                    <xsd:enumeration value="NON RECU"></xsd:enumeration>
                </xsd:restriction>  
            </xsd:simpleType> 
        </xsd:attribute>
    </xsd:complexType>   
    <xsd:complexType name="T_ED">
        <xsd:attribute name="cin" type="xsd:string" use="required"> </xsd:attribute>
        <xsd:attribute name="nom" type="xsd:string" use="required"> </xsd:attribute>
        <xsd:attribute name="prenom" type="xsd:string" use="required"> </xsd:attribute>
        <xsd:attribute name="ville" type="xsd:string" use="required"> </xsd:attribute>
    </xsd:complexType>   
</xsd:schema>

=== saadehm80/XML-DTD-XSLT/Mondat/mandat2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rapport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/hp/Downloads/videos%20cours%20youtube/XML/Exemples%20XML/Mondat/mandat.xsd">
    <mandat num="7124536" date="2007-10-10" montant="1000" etat="RECU">
        <expediteur cin="A12345" nom="Slimani" prenom="Youssef" ville="Casa"/>
        <destinateur cin="P98654" nom="Hassouni" prenom="Laila" ville="Fes"/>
    </mandat>
    <mandat num="7124537" date="2007-11-11" montant="3200" etat="NON RECU">
        <expediteur cin="M12345" nom="Alaoui" prenom="Mohamed" ville="Marakech"/>
        <destinateur cin="M92654" nom="Alaoui" prenom="Imane" ville="Fes"/>
    </mandat>
    <mandat num="7124538" date="2008-07-08" montant="500" etat="NON RECU">
        <expediteur cin="H123222" nom="Qasmi" prenom="Slim" ville="Oujda"/>
        <destinateur cin="B91154" nom="Qasmi" prenom="Hassan" ville="Rabat"/>
    </mandat>
</rapport>
