=== saadehm80/XML-DTD-XSLT/operateur_telephonique/operateur.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    <xsd:element name="operateur">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="client" maxOccurs="unbounded" type="T_CLIENT">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="T_CLIENT">
        <xsd:sequence>
            <xsd:element name="abonnement" maxOccurs="unbounded" type="T_ABON">
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="code" type="xsd:string" use="required"> </xsd:attribute>
        <xsd:attribute name="nom" type="xsd:string" use="required"> </xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="T_ABON">
        <xsd:sequence>
            <xsd:element name="facture" maxOccurs="unbounded" type="T_FACT">
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="numAb" type="xsd:int" use="required"> </xsd:attribute>
        <xsd:attribute name="dateAb" type="xsd:date" use="required"> </xsd:attribute>
        <xsd:attribute name="type" default="GSM">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="GSM"></xsd:enumeration>
                <xsd:enumeration value="Fixe"></xsd:enumeration>
                <xsd:enumeration value="Internet"></xsd:enumeration>
            </xsd:restriction>  
        </xsd:simpleType> 
        </xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="T_FACT">
        <xsd:attribute name="numFact" type="xsd:int" use="required"></xsd:attribute>
        <xsd:attribute name="dateFact" type="xsd:date" use="required"></xsd:attribute>
        <xsd:attribute name="montant" type="xsd:double" use="required"></xsd:attribute>
        <xsd:attribute name="reglee" default="Non">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
              <xsd:enumeration value="Oui"></xsd:enumeration>
              <xsd:enumeration value="Non"></xsd:enumeration>
          </xsd:restriction>  
        </xsd:simpleType> 
        </xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== saadehm80/XML-DTD-XSLT/Operateur telephonique/operateur1.xml
<?xml version="1.0" encoding="UTF-8"?>

<operateur xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"   xsi:noNamespaceSchemaLocation="./operateur.xsd">
    <client code="1" nom="A">
        <abonnement numAb="111" dateAb="2012-12-11" type="GSM">
            <facture numFact="444" dateFact="2012-10-10" montant="9700.45" reglee="Non"/>
            <facture numFact="333" dateFact="2012-11-10" montant="8700.45" reglee="Oui"/>
            <facture numFact="222" dateFact="2012-10-10" montant="7700.45" reglee="Non"/>
        </abonnement>
        <abonnement numAb="222" dateAb="2012-12-11" type="Fixe">
            <facture numFact="555" dateFact="2012-11-10" montant="8700.45" reglee="Oui"/>
            <facture numFact="222" dateFact="2012-10-10" montant="7700.45" reglee="Non"/>
        </abonnement>
    </client>
    <client code="2" nom="B">
        <abonnement numAb="333" dateAb="2012-12-11" type="GSM">
            <facture numFact="777" dateFact="2012-10-10" montant="2700.45" reglee="Non"/>
            <facture numFact="555" dateFact="2012-10-10" montant="5700.45" reglee="Non"/>
        </abonnement>
        <abonnement numAb="441" dateAb="2012-12-11" type="Fixe">
            <facture numFact="551" dateFact="2012-11-10" montant="700.45" reglee="Oui"/>
            <facture numFact="552" dateFact="2012-10-10" montant="750.45" reglee="Non"/>
            <facture numFact="999" dateFact="2012-11-10" montant="4700.45" reglee="Oui"/>
        </abonnement>
    </client>
</operateur>
