=== saadehm80/XML-DTD-XSLT/mandat/mandat.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT rapport (mandat+) >
<!ELEMENT mandat (expediteur,destinataire) >
<!-- <!ELEMENT mandat (expediteur,destinataire) > on s'en fou de l'ordre -->
<!ELEMENT  expediteur EMPTY>
<!ELEMENT  destinataire EMPTY>

<!ATTLIST mandat 
             num     CDATA #REQUIRED
             date    CDATA #REQUIRED
             montant CDATA #REQUIRED
             etat (Recu|Non_Recu) 'Non_Recu'>
<!ATTLIST expediteur 
             cin    NMTOKEN #REQUIRED
             nom    CDATA   #REQUIRED
             prenom CDATA   #REQUIRED
             ville  CDATA   #IMPLIED>
             
<!ATTLIST destinataire 
             cin    NMTOKEN #REQUIRED
             nom    CDATA   #REQUIRED
             prenom CDATA   #REQUIRED
             ville  CDATA   #IMPLIED>

=== saadehm80/XML-DTD-XSLT/mandat/mandat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rapport SYSTEM "./mandat.dtd">
<rapport>
    <mandat num="7124536" date="2007-1-1" montant="1000" etat="Recu">
        <expediteur cin="A12345" nom="Slimani" prenom="Youssef" ville="Casa"/>
        <destinataire cin="P98654" nom="Hassouni" prenom="Laila" ville="Fes"/>
    </mandat>
    <mandat num="7124537" date="2007-1-1" montant="3200" etat="Non_Recu">
        <expediteur cin="M12345" nom="Alaoui" prenom="Mohamed" ville="Marakech"/>
        <destinataire cin="M92654" nom="Alaoui" prenom="Imane" ville="Fes"/>
    </mandat>
    <mandat num="7124538" date="2007-1-1" montant="500" etat="Recu">
        <expediteur cin="H123222" nom="Qasmi" prenom="Slim" ville="Oujda"/>
        <destinataire cin="B91154" nom="Qasmi" prenom="Hassan" ville="Rabat"/>
    </mandat>
</rapport>
